#!/usr/bin/env bash

set +ex

SCRIPT=$(realpath "$0")
DIR=$(dirname "$SCRIPT")

. "$DIR/../utils/pretty_echo.sh" --source-only

title "Running brew setup"
info "checking if brew binary is present."

if test ! "$(command -v brew)"; then
	warning "brew binary not found, installing brew;"
	NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

info "brew installed, setting up packages and casks"
brew bundle --file "$DIR/utils/Brewfile"

info "Successfully setup brew"
