[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.class]
general = "alacritty"
instance = "alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 4

[window.position]
x = 0
y = 0
