#!/usr/bin/env bash

if ! [ -d "$HOME/.config/oh-my-zsh" ]; then
	sh -c "$(ZSH="$HOME/.config/oh-my-zsh" curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "ZSH=\"$HOME/.config/oh-my-zsh\"" --unattended
fi

echo "Oh My Zsh installed at $HOME/.config/oh-my-zsh"

# Set custom plugin theme
ZSH_CUSTOM="$HOME/.config/oh-my-zsh/custom"

# Define plugins as name|git repo
PLUGINS=(
	"zsh-syntax-highlighting|https://github.com/zsh-users/zsh-syntax-highlighting.git"
	"zsh-autosuggestions|https://github.com/zsh-users/zsh-autosuggestions.git"
	"zsh-completions|https://github.com/zsh-users/zsh-completions"
	"zsh-nvm|https://github.com/lukechilds/zsh-nvm"
)
# Install plugins
for plugin in "${PLUGINS[@]}"; do
	IFS='|' read -ra ADDR <<<"${plugin}"
	plugin_name=${ADDR[0]}
	git_repo=${ADDR[1]}
	if [ ! -d "$ZSH_CUSTOM/plugins/$plugin_name" ]; then
		echo "$plugin_name is not present at $ZSH_CUSTOM/plugins/$plugin_name, installing it via $git_repo"
		git clone "$git_repo" "$ZSH_CUSTOM/plugins/$plugin_name"
	fi
	echo "$plugin_name installed at $ZSH_CUSTOM/plugins/$plugin_name   "
done
