# Configuration for Alacritty, the GPU enhanced terminal emulator

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
import:
 - ~/.config/alacritty/themes/tokoynight_storm.yml

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`
  # TERM: alacritty
  TERM: xterm-256color
  # TERM: nvim

window:
  # Window title
  title: Alacritty
  # padding:
  #   x: 10
  #   y: 4
  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

font:
  normal:
    family: "MesloLGS NF"
  # Point size of the font
  size: 15.0

# Colors (Hyper)
# colors:
#   Default colors
#   primary:
#     background: '0x000000'
#     foreground: '0xffffff'
#
#     # Bright and dim foreground colors
#     #
#     # The dimmed foreground color is calculated automatically if it is not
#     # present. If the bright foreground color is not set, or
#     # `draw_bold_text_with_bright_colors` is `false`, the normal foreground
#     # color will be used.
#     dim_foreground: '#828482'
#     bright_foreground: '#eaeaea'
#
#   # Cursor colors
#   #
#   # Colors which should be used to draw the terminal cursor.
#   #
#   # Allowed values are CellForeground/CellBackground, which reference the
#   # affected cell, or hexadecimal colors like #ff00ff.
#   cursor:
#     text: CellBackground
#     cursor: CellForeground
#
#      # Vi mode cursor colors
#   #
#   # Colors for the cursor when the vi mode is active.
#   #
#   # Allowed values are CellForeground/CellBackground, which reference the
#   # affected cell, or hexadecimal colors like #ff00ff.
#   vi_mode_cursor:
#     text: CellBackground
#     cursor: CellForeground
#
#   # Search colors
#   #
#   # Colors used for the search bar and match highlighting.
#   search:
#     #  Allowed values are CellForeground/CellBackground, which reference the
#     #  affected cell, or hexadecimal colors like #ff00ff.
#     matches:
#       foreground: '#000000'
#       background: '#ffffff'
#     focused_match:
#       foreground: '#ffffff'
#       background: '#000000'
#
#     bar:
#       background: '#c5c8c6'
#       foreground: '#1d1f21'
#
#   # Keyboard regex hints
#   hints:
#          # First character in the hint label
#     #
#     # Allowed values are CellForeground/CellBackground, which reference the
#     # affected cell, or hexadecimal colors like #ff00ff.
#     start:
#       foreground: '#1d1f21'
#       background: '#e9ff5e'
#
#     # All characters after the first one in the hint label
#     #
#     # Allowed values are CellForeground/CellBackground, which reference the
#     # affected cell, or hexadecimal colors like #ff00ff.
#     end:
#       foreground: '#e9ff5e'
#       background: '#1d1f21'
#
#   # Line indicator
#   #
#   # Color used for the indicator displaying the position in history during
#   # search and vi mode.
#   #
#   # By default, these will use the opposing primary color.
#   line_indicator:
#     foreground: None
#     background: None
#
#     # Selection colors
#   #
#   # Colors which should be used to draw the selection area.
#   #
#   # Allowed values are CellForeground/CellBackground, which reference the
#   # affected cell, or hexadecimal colors like #ff00ff.
#   selection:
#     text: CellBackground
#     background: CellForeground
#
#   # Normal colors
#   normal:
#     black:   '0x000000'
#     red:     '0xfe0100'
#     green:   '0x33ff00'
#     yellow:  '0xfeff00'
#     blue:    '0x0066ff'
#     magenta: '0xcc00ff'
#     cyan:    '0x00ffff'
#     white:   '0xd0d0d0'
#
#   # Bright colors
#   bright:
#     black:   '0x808080'
#     red:     '0xfe0100'
#     green:   '0x33ff00'
#     yellow:  '0xfeff00'
#     blue:    '0x0066ff'
#     magenta: '0xcc00ff'
#     cyan:    '0x00ffff'
#     white:   '0xFFFFFF'
#
  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  # dim:
  #   black:   '#131415'
  #   red:     '#864343'
  #   green:   '#777c44'
  #   yellow:  '#9e824c'
  #   blue:    '#556a7d'
  #   magenta: '#75617b'
  #   cyan:    '#5b7d78'
  #   white:   '#828482'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  #indexed_colors: []


key_bindings:
  - { key: Paste,                                       action: Paste          }
  - { key: Copy,                                        action: Copy           }
  - { key: L,         mods: Control,                    action: ClearLogNotice }
  - { key: L,         mods: Control, mode: ~Search, chars: "\x0c"          }
  - { key: L,         mods: Control, mode: ~Vi, chars: "\x0c"          }
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }
  # Search Mode
  # - { key: Return,                mode: Vi,  action: SearchConfirm         }
  - { key: Return,                mode: Search,  action: SearchConfirm         }
  - { key: Escape,                mode: Search,     action: SearchCancel          }
  - { key: C,      mods: Control, mode: Search,     action: SearchCancel          }
  - { key: U,      mods: Control, mode: Search,     action: SearchClear           }
  - { key: W,      mods: Control, mode: Search,     action: SearchDeleteWord      }
  - { key: P,      mods: Control, mode: Search,     action: SearchHistoryPrevious }
  - { key: N,      mods: Control, mode: Search,     action: SearchHistoryNext     }
  - { key: Up,                    mode: Search,     action: SearchHistoryPrevious }
  - { key: Down,                  mode: Search,     action: SearchHistoryNext     }
  - { key: Return,                mode: Search, action: SearchFocusNext       }
  - { key: Return, mods: Shift,   mode: Search, action: SearchFocusPrevious   }
  # - { key: Return,                mode: Vi, action: SearchFocusNext       }
  # - { key: Return, mods: Shift,   mode: Vi, action: SearchFocusPrevious   }
  # (macOS only)
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word
  - { key: K,              mods: Command, mode: ~Vi, chars: "\x0c"                 }
  - { key: K,              mods: Command, mode: ~Vi, action: ClearHistory          }
  - { key: K,              mods: Command, mode: ~Search, chars: "\x0c"                 }
  - { key: K,              mods: Command, mode: ~Search, action: ClearHistory          }
  - { key: Key0,           mods: Command,                    action: ResetFontSize         }
  - { key: Equals,         mods: Command,                    action: IncreaseFontSize      }
  - { key: Plus,           mods: Command,                    action: IncreaseFontSize      }
  - { key: NumpadAdd,      mods: Command,                    action: IncreaseFontSize      }
  - { key: Minus,          mods: Command,                    action: DecreaseFontSize      }
  - { key: NumpadSubtract, mods: Command,                    action: DecreaseFontSize      }
  - { key: V,              mods: Command,                    action: Paste                 }
  - { key: C,              mods: Command,                    action: Copy                  }
  - { key: C,              mods: Command, mode: Search,  action: ClearSelection        }
  - { key: C,              mods: Command, mode: Vi,  action: ClearSelection        }
  - { key: H,              mods: Command,                    action: Hide                  }
  # - { key: H,              mods: Command|Alt,                action: HideOtherApplications }
  # - { key: H,              mods: Command|Alt,                action: HideOtherApplications }
  - { key: M,              mods: Command,                    action: Minimize              }
  - { key: Q,              mods: Command,                    action: Quit                  }
  - { key: W,              mods: Command,                    action: Quit                  }
  - { key: N,              mods: Command,                    action: SpawnNewInstance      }
  - { key: F,              mods: Command|Control,            action: ToggleFullscreen      }
  - { key: F,              mods: Command, mode: ~Search,     action: SearchForward         }
  - { key: B,              mods: Command, mode: ~Search,     action: SearchBackward        }
  - { key: Key0, mods: Alt, chars: 'º' }
  - { key: Key1, mods: Alt, chars: '¡' }
  - { key: Key2, mods: Alt, chars: '€' }
  - { key: Key3, mods: Alt, chars: '#' }
  - { key: Key4, mods: Alt, chars: '¢' }
  - { key: Key5, mods: Alt, chars: '∞' }
  - { key: Key6, mods: Alt, chars: '§' }
  - { key: Key7, mods: Alt, chars: '¶' }
  - { key: Key8, mods: Alt, chars: '•' }
  - { key: Key9, mods: Alt, chars: 'ª' }
