[colors.bright]
black = "0x5c6370"
blue = "0x8fc6f4"
cyan = "0x7bc6d0"
green = "0xb3d39c"
magenta = "0xd7a1e7"
red = "0xe06c75"
white = "0xe6e6e6"
yellow = "0xb3d38c"

[colors.normal]
black = "0x454a54"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xd7427f"
white = "0xcdcdcd"
yellow = "0xe5c07b"

[colors.primary]
background = "0x21252b"
foreground = "0x9da5b4"

[theme_insomnia.bright]
black = "0x5c6370"
blue = "0x8fc6f4"
cyan = "0x7bc6d0"
green = "0xb3d39c"
magenta = "0xd7a1e7"
red = "0xe06c75"
white = "0xe6e6e6"
yellow = "0xb3d38c"

[theme_insomnia.normal]
black = "0x454a54"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xd7427f"
white = "0xcdcdcd"
yellow = "0xe5c07b"

[theme_insomnia.primary]
background = "0x21252b"
foreground = "0x9da5b4"
