[colors.bright]
black = "0x414458"
blue = "0x556fff"
cyan = "0x3fdcee"
green = "0x18e3c8"
magenta = "0xb043d1"
red = "0xff4971"
white = "0xbebec1"
yellow = "0xff8037"

[colors.normal]
black = "0x282a36"
blue = "0x8897f4"
cyan = "0x79e6f3"
green = "0x5adecd"
magenta = "0xc574dd"
red = "0xf37f97"
white = "0xfdfdfd"
yellow = "0xf2a272"

[colors.primary]
background = "0x1d1f28"
foreground = "0xfdfdfd"

[theme_lovelace.bright]
black = "0x414458"
blue = "0x556fff"
cyan = "0x3fdcee"
green = "0x18e3c8"
magenta = "0xb043d1"
red = "0xff4971"
white = "0xbebec1"
yellow = "0xff8037"

[theme_lovelace.normal]
black = "0x282a36"
blue = "0x8897f4"
cyan = "0x79e6f3"
green = "0x5adecd"
magenta = "0xc574dd"
red = "0xf37f97"
white = "0xfdfdfd"
yellow = "0xf2a272"

[theme_lovelace.primary]
background = "0x1d1f28"
foreground = "0xfdfdfd"
